import Head from 'next/head';
import { Geist, Geist_Mono } from 'next/font/google';
import VideoPlayer from '@/components/VideoPlayer';
// import KinescopePlayer from '@kinescope/react-kinescope-player';
import dynamic from 'next/dynamic';
const KinescopePlayer = dynamic(() => import('@kinescope/react-kinescope-player'), { ssr: false });

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export default function Home() {
    // const kinescopeVideoId = 'https://kinescope.io/85UMa3CwCBFxcWzgn5hDY3';
    const kinescopeVideoId = 'cuFaFFHjKpC3KMQyZXjpxE';
    // const youtubeVideoId = 'https://www.youtube.com/watch?v=tZ9Q8sXGRi8&ab_channel=FAANGSchool';

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`${geistSans.variable} ${geistMono.variable}`}>
                <div>
                    <h2>Kinescope Video</h2>
                    {/* <VideoPlayer videoId={kinescopeVideoId} type="kinescope" /> */}
                    <VideoPlayer url={'https://kinescope.io/85UMa3CwCBFxcWzgn5hDY3'} />
                    <hr></hr>
                    <KinescopePlayer videoId={kinescopeVideoId}></KinescopePlayer>
                </div>
            </div>
        </>
    );
}
