import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import FullscreenVideo from "@/components/FullscreenVideo";
import VideoPlayer from "@/components/VideoPlayer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  // const kinescopeVideoId = 'https://kinescope.io/85UMa3CwCBFxcWzgn5hDY3';
  const kinescopeVideoId = 'cuFaFFHjKpC3KMQyZXjpxE';
  // const youtubeVideoId = 'https://www.youtube.com/watch?v=tZ9Q8sXGRi8&ab_channel=FAANGSchool';


  return (
      <>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className={`${geistSans.variable} ${geistMono.variable}`}>
              <div>
                  <h2>Kinescope Video</h2>
                  <VideoPlayer videoId={kinescopeVideoId} type="kinescope" />

        </div>
            <div>
      <h2>Kinescope Video</h2>
      <FullscreenVideo videoId={kinescopeVideoId} type="kinescope" />

    </div>
          </div>
      </>
  );
}
